# -*- coding: utf-8 -*-
"""Regression_poly_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZrzW82ltrvJSdxI53CJwTZuT9VASqFV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("Salaries.csv")
df.head()

x=df.iloc[:, 1:2].values
y=df.iloc[:,2].values

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.2)

# data scalling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.fit_transform(xtest)

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)

plt.scatter(x,y, color='red')
plt.plot(x, lin_reg.predict(x), color='blue')
plt.title('Linear Regression')
plt.show()

from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=10)
x_poly=poly_reg.fit_transform(x)

poly_model=LinearRegression()
poly_model.fit(x_poly, y)

poly_model.predict(poly_reg.fit_transform([[5.5]]))

plt.scatter(x,y, color='red')
plt.plot(x, poly_model.predict(poly_reg.fit_transform(x)), color='blue')
plt.title('Polynomial Regression')
plt.show()